(if (fboundp 'normal-top-level-add-subdirs-to-load-path)
        (let* ((my-lisp-dir "~/.emacs.d/site-lisp")
               (default-directory my-lisp-dir))
         (setq load-path (cons my-lisp-dir load-path))
 (normal-top-level-add-subdirs-to-load-path)))
